[92m
CallInLoop.bad() has external calls inside a loop: "destinations[i].transfer(i)" (tests/multiple_calls_in_loop.sol#11)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation/#calls-inside-a-loop[0m
tests/multiple_calls_in_loop.sol analyzed (1 contracts with 1 detectors), 1 result(s) found
